extends SceneTree

const ContentRegistryTests := preload("res://tests/content/test_content_registry.gd")
const ContentSchemaRegistryTests := preload("res://tests/content/test_content_schema_registries.gd")
const SemanticRoleSchemaRegistryTests := preload("res://tests/content/test_semantic_role_schema_registry.gd")
const ContentValidationPipelineTests := preload("res://tests/content/test_content_validation_pipeline.gd")
const ContentValidationEvidenceTests := preload("res://tests/content/test_content_validation_evidence.gd")
const ContentValidationEvidenceConsumerTests := preload("res://tests/content/test_content_validation_evidence_consumers.gd")
const ArchetypeContractTests := preload("res://tests/content/test_archetype_contract.gd")
const ArchetypeRealizationTests := preload("res://tests/content/test_archetype_realization.gd")
const ItemContractTests := preload("res://tests/content/test_item_contract.gd")
const ResourceContractTests := preload("res://tests/content/test_resource_contract.gd")
const CreatureContractTests := preload("res://tests/content/test_creature_contract.gd")
const WeaponContractTests := preload("res://tests/content/test_weapon_contract.gd")
const WeaponRuntimeProductionTests := preload("res://tests/content/test_weapon_runtime_production.gd")
const WeaponRuntimeFailureTests := preload("res://tests/content/test_weapon_runtime_failure_contract.gd")
const WeaponRuntimeSessionCompositionTests := preload("res://tests/content/test_weapon_runtime_session_composition.gd")
const WeaponRuntimeSessionFailureCompositionTests := preload("res://tests/content/test_weapon_runtime_session_failure_composition.gd")
const ReservedSiteAssignmentTests := preload("res://tests/content/test_reserved_site_assignment.gd")
const UndergroundPlacementTests := preload("res://tests/content/test_underground_placement.gd")
const SurfaceHarvestContentTests := preload("res://tests/content/test_surface_harvest_content.gd")
const LootContractTests := preload("res://tests/content/test_loot_contract.gd")
const CraftingContractTests := preload("res://tests/crafting/test_crafting_contract.gd")


func _init() -> void:
	var failures: Array[String] = []
	failures.append_array(ContentRegistryTests.run())
	failures.append_array(ContentSchemaRegistryTests.run())
	failures.append_array(SemanticRoleSchemaRegistryTests.run())
	failures.append_array(ContentValidationPipelineTests.run())
	failures.append_array(ContentValidationEvidenceTests.run())
	failures.append_array(ContentValidationEvidenceConsumerTests.run())
	failures.append_array(ArchetypeContractTests.run())
	failures.append_array(ArchetypeRealizationTests.run())
	failures.append_array(ItemContractTests.run())
	failures.append_array(ResourceContractTests.run())
	failures.append_array(CreatureContractTests.run())
	failures.append_array(WeaponContractTests.run())
	failures.append_array(WeaponRuntimeProductionTests.run())
	failures.append_array(WeaponRuntimeFailureTests.run())
	failures.append_array(WeaponRuntimeSessionCompositionTests.run())
	failures.append_array(WeaponRuntimeSessionFailureCompositionTests.run())
	failures.append_array(ReservedSiteAssignmentTests.run())
	failures.append_array(UndergroundPlacementTests.run())
	failures.append_array(SurfaceHarvestContentTests.run())
	failures.append_array(LootContractTests.run())
	failures.append_array(CraftingContractTests.run())
	if failures.is_empty():
		print("[VALIDATION] PASS content")
		print("  semantic content ids / deterministic registry / category-capability-role schemas / headless validation + snapshot evidence + stale-consumer guards / archetype realization / item / resource / creature / weapon / production weapon runtime + session composition + presentation-failure boundary + failure atomicity / reserved-site assignment / underground placement / surface-harvest / loot / crafting rulebook contracts passed")
		quit(0)
		return

	printerr("[VALIDATION] FAIL content — %d failure(s)" % failures.size())
	for failure in failures:
		printerr("  - " + failure)
	quit(1)
